### ISSUE TITLE
ModuleNotFoundError: No module named 'anonymizer'

### ISSUE THREAD

**Issue by AlexanderKozhevin** [understand-ai/anonymizer#12]
I tried to run in google colab, but getting an error. 

Here is the notebook. 
https://colab.research.google.com/drive/15SG5mYhFezEhwl4Za0qF9WPBNH4R2Ffj?usp=sharing

**Comment by Clemens-E** [comment]
![image](https://user-images.githubusercontent.com/43886026/85706301-5994a780-b6e2-11ea-9a5b-fb02e618ebf1.png)
I'm having the same issue, pytest passes but I can't run it

**Comment by Clemens-E** [comment]
I dont have any python knowledge but this is what I came up with 
(**_it's rather a workaround than a fix_**)
```py
import sys
sys.path.append('./anonymization')
sys.path.append('./detection')
sys.path.append('./obfuscation')
from anonymizer import Anonymizer
from detector import Detector
from weights import download_weights, get_weights_path
from obfuscator import Obfuscator
```
and repeat this for every other import of the files

**Comment by t-raww187** [comment]
I get the same mistake, you know how to fix it?

**Comment by AlexanderKozhevin** [comment]
@Clemens-E Hello, sorry can you provide code sample or colab notebook?
I still don't understand how to get it started

**Comment by Clemens-E** [comment]
Sure, so the problem is that python cant find the other files (or isn't aware that they exist)
I came up with this workaround (**if you want a clean solution, don't use this**)

You import sys and add every file you want to import from to the path, you have to redo this for every file that imports from another file. 

for `bin/anonimize.py`:
```py
import sys
sys.path.append('./anonymization')
sys.path.append('./detection')
sys.path.append('./obfuscation')
from anonymizer import Anonymizer
from detector import Detector
from weights import download_weights, get_weights_path
from obfuscator import Obfuscator
```

for `detection/detector.py`:
```py
import sys
sys.path.append('./utils')
from box import Box
from helpers import get_default_session_config
```
I think that's it

**Comment by Tiberius1OOO** [comment]
> Sure, so the problem is that python cant find the other files (or isn't aware that they exist)
> I came up with this workaround (**if you want a clean solution, don't use this**)
> 
> You import sys and add every file you want to import from to the path, you have to redo this for every file that imports from another file.
> 
> for `bin/anonimize.py`:
> 
> ```python
> import sys
> sys.path.append('./anonymization')
> sys.path.append('./detection')
> sys.path.append('./obfuscation')
> from anonymizer import Anonymizer
> from detector import Detector
> from weights import download_weights, get_weights_path
> from obfuscator import Obfuscator
> ```
> 
> for `detection/detector.py`:
> 
> ```python
> import sys
> sys.path.append('./utils')
> from box import Box
> from helpers import get_default_session_config
> ```
> 
> I think that's it

Sadly that did not fix anything. and this is litterally what is preventing me from starting this

**Comment by Clemens-E** [comment]
Hm, that's weird. It worked (and still works) for me, and from the 🎉 reaction I'm guessing that it worked for @AlexanderKozhevin aswell?

I haven't looked into it any further because it doesn't work well enough for my use case, and this project seems rather dead. So that's all I can say about this, good luck tho!

**Comment by Tiberius1OOO** [comment]
```
Traceback (most recent call last):
  File "anonymizer/bin/anonymize.py", line 20, in <module>
    from anonymizer.anonymization import Anonymizer
ModuleNotFoundError: No module named 'anonymizer'
```


pytest works fine saddly the solution did not work at all.

Please if anyone can help I would be super thrilled

**Comment by lidiador** [comment]
If you are on Windows, a simple `set PYTHONPATH=%PYTHONPATH%;.` before running the script should do the trick.

**Comment by m-o-n-t-i** [comment]
> If you are on Windows, a simple `set PYTHONPATH=%PYTHONPATH%;.` before running the script should do the trick.

Did it for me- thank you! 👍

**Comment by frantz03** [comment]
Hey! 
What did the trick for me with Ubuntu 20.04 was to take away the / before path: 
`PYTHONPATH=$PYTHONPATH:. python anonymizer/bin/anonymize.py --input path/to/input_folder --image-output path/to/output_folder --weights path/to/store/weights `
