### ISSUE TITLE
Operation, 'image_tensor', does not exist in the graph

### ISSUE THREAD

**Issue by ticlazau** [understand-ai/anonymizer#15]
Hello,

I am getting this error when running pytest and the same when running nonymizer/bin/anonymize.py

`Anonymizing images in input/ and saving the anonymized images to output/...
  0%|                                                                                                                                                                           | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "anonymizer/bin/anonymize.py", line 104, in <module>
    write_json=args.write_detections, obfuscation_parameters=args.obfuscation_kernel)
  File "anonymizer/bin/anonymize.py", line 96, in main
    write_json=write_json)
  File "/home/coredump/projects/anonymizer/anonymizer/anonymization/anonymizer.py", line 68, in anonymize_images
    anonymized_image, detections = self.anonymize_image(image=image, detection_thresholds=detection_thresholds)
  File "/home/coredump/projects/anonymizer/anonymizer/anonymization/anonymizer.py", line 45, in anonymize_image
    new_boxes = detector.detect(image, detection_threshold=detection_thresholds[kind])
  File "/home/coredump/projects/anonymizer/anonymizer/detection/detector.py", line 39, in detect
    image_tensor = self.detection_graph.get_tensor_by_name('image_tensor:0')
  File "/home/coredump/anaconda3/envs/anonymizer/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3783, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/home/coredump/anaconda3/envs/anonymizer/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3607, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/coredump/anaconda3/envs/anonymizer/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3649, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))'

'**KeyError: "The name 'image_tensor:0' refers to a Tensor which does not exist. The operation, 'image_tensor', does not exist in the graph.**"
`
Anyone with this issue? I am using TF 1.15.4

Rgds,
FM

**Comment by jonasmeyer1** [comment]
I got the same error when running pytest and anonymizer/bin/anonymize.py .
I tested it on both windows 10 and ubuntu 16.04 with tensorflow 1.11.0 and tensorflow-gpu 1.11.0

The error message from pytest:
(anonymizer) C:\Users\...\_Data\anonymizer>pytest
============================= test session starts =============================
platform win32 -- Python 3.6.9, pytest-3.9.1, py-1.9.0, pluggy-0.13.1
rootdir: C:\Users\...\_Data\anonymizer, inifile: pytest.ini
collected 6 items

test\anonymization\anonymizer_test.py ..                                 [ 33%]
test\detection\detector_test.py F                                        [ 50%]
test\detection\weights_test.py .                                         [ 66%]
test\obfuscation\obfuscator_test.py .                                    [ 83%]
test\utils\box_test.py .                                                 [100%]

================================== FAILURES ===================================
_________________ TestDetector.test_it_detects_obvious_faces __________________

tmp_path = WindowsPath('C:/Users/.../AppData/Local/Temp/pytest-of-jonas.meyer/pytest-1/test_it_detects_obvious_faces0')

    @staticmethod
    def test_it_detects_obvious_faces(tmp_path):
        weights_directory = tmp_path / 'weights'
        face_weights_path = get_weights_path(weights_directory, kind='face')
        download_weights(weights_directory)

        detector = Detector(kind='face', weights_path=face_weights_path)
        np_image = load_np_image('./test/detection/face_test_image.jpg')

        left_face = Box(x_min=267, y_min=64, x_max=311, y_max=184, score=0.0, kind='face')
        right_face = Box(x_min=369, y_min=68, x_max=420, y_max=152, score=0.0, kind='face')

>       boxes = detector.detect(np_image, detection_threshold=0.2)

test\detection\detector_test.py:33:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
anonymizer\detection\detector.py:39: in detect
    image_tensor = self.detection_graph.get_tensor_by_name('image_tensor:0')
..\..\appdata\local\continuum\miniconda3\lib\site-packages\tensorflow\python\framework\ops.py:3664: in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
..\..\appdata\local\continuum\miniconda3\lib\site-packages\tensorflow\python\framework\ops.py:3488: in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tensorflow.python.framework.ops.Graph object at 0x000001F80C8099B0>
obj = 'image_tensor:0', allow_tensor = True, allow_operation = False

    def _as_graph_element_locked(self, obj, allow_tensor, allow_operation):
      """See `Graph.as_graph_element()` for details."""
      # The vast majority of this function is figuring
      # out what an API user might be doing wrong, so
      # that we can give helpful error messages.
      #
      # Ideally, it would be nice to split it up, but we
      # need context to generate nice error messages.

      if allow_tensor and allow_operation:
        types_str = "Tensor or Operation"
      elif allow_tensor:
        types_str = "Tensor"
      elif allow_operation:
        types_str = "Operation"
      else:
        raise ValueError("allow_tensor and allow_operation can't both be False.")

      temp_obj = _as_graph_element(obj)
      if temp_obj is not None:
        obj = temp_obj

      # If obj appears to be a name...
      if isinstance(obj, compat.bytes_or_text_types):
        name = compat.as_str(obj)

        if ":" in name and allow_tensor:
          # Looks like a Tensor name and can be a Tensor.
          try:
            op_name, out_n = name.split(":")
            out_n = int(out_n)
          except:
            raise ValueError("The name %s looks a like a Tensor name, but is "
                             "not a valid one. Tensor names must be of the "
                             "form \"<op_name>:<output_index>\"." % repr(name))
          if op_name in self._nodes_by_name:
            op = self._nodes_by_name[op_name]
          else:
            raise KeyError("The name %s refers to a Tensor which does not "
                           "exist. The operation, %s, does not exist in the "
>                          "graph." % (repr(name), repr(op_name)))
E           KeyError: "The name 'image_tensor:0' refers to a Tensor which does not exist. The operation, 'image_tensor', does not exist in the graph."

..\..\appdata\local\continuum\miniconda3\lib\site-packages\tensorflow\python\framework\ops.py:3530: KeyError
---------------------------- Captured stdout call -----------------------------
Downloading face weights to C:\Users\...\weights_face_v1.0.0.pb
Downloading 1CwChAYxJo3mON6rcvXsl82FMSKj82vxF into C:\Users\...\weights_face_v1.0.0.pb... Done.
Downloading plate weights to C:\Users\...\weights_plate_v1.0.0.pb
Downloading 1Fls9FYlQdRlLAtw-GVS_ie1oQUYmci9g into C:\Users\...\weights_plate_v1.0.0.pb... Done.
---------------------------- Captured stderr call -----------------------------
2020-10-22 07:51:54.716741: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
============================== warnings summary ===============================
C:\Users\...\anonymizer\anonymizer\detection\detector.py:16: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  od_graph_def.ParseFromString(serialized_graph)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=============== 1 failed, 5 passed, 1 warnings in 4.89 seconds ================

**Comment by jonasmeyer1** [comment]
I managed to run pytest and anonymizer/bin/anonymize.py correctly. I reinstalled the nvidia driver and updated the CUDA version. Now it works fine on the GPU.

**Comment by ticlazau** [comment]
Hi @jonasmeyer1 
Can you share your GPU driver and CUDA version?

Thx

**Comment by jonasmeyer1** [comment]
Graphics Card: Nvidia GeForce GTX 1080 Ti 
Driver Version: 455.32.0
CUDA Version: 11.1


I've also tested it on cpu and it works now too.

**Comment by ticlazau** [comment]
Thx @jonasmeyer1  

final question have you this working with TensorFlow 1.11.0 or 1.15?

**Comment by jonasmeyer1** [comment]
I made it work with TensorFlow 1.11.0.

**Comment by ticlazau** [comment]
Thank you

**Comment by federicochiesa** [comment]
I'm running Ubuntu 20.04 with CUDA 11.1. If I try to use TF 1.11.0 I get the error "ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory", while if I use TF 1.15.0 I get the same error as the author of the issue. Is there a way to fix this?

**Comment by jonasmeyer1** [comment]
I think you have to install CUDA 9, since TF1.11 requires this version. An additional source of  error could be the compiler version, where GCC 4.8 is needed.
Here you can find the dependencies of all TF versions: https://www.tensorflow.org/install/source#tested_build_configurations

Contrary to my [comment](https://github.com/understand-ai/anonymizer/issues/15#issuecomment-719450187) above I use CUDA toolkit 9.0.

**Comment by venn0605** [comment]
> Graphics Card: Nvidia GeForce GTX 1080 Ti Driver Version: 455.32.0 CUDA Version: 11.1
> 
> I've also tested it on cpu and it works now too.

Hi, the TensorFlow 1.11.0 corresponds with CUDA 9. Does CUDA Version: 11.1work? It seems weird.

**Comment by jonasmeyer1** [comment]
Hi, 
Sorry for the confusion. My first comment was wrong as mentioned [here](https://github.com/understand-ai/anonymizer/issues/15#issuecomment-818457042), I used the CUDA Version 9.0 not 11.1.

**Comment by venn0605** [comment]
> Hi, Sorry for the confusion. My first comment was wrong as mentioned [here](https://github.com/understand-ai/anonymizer/issues/15#issuecomment-818457042), I used the CUDA Version 9.0 not 11.1.

Do you ever run this code in the tensorflow CPU version? Is it smoothly? When I run this code in the CPU version, some problems occurs, such tf.Session().

**Comment by jonasmeyer1** [comment]
I tested it once in CPU version. But since the GPU version is faster, I didn't continue using the CPU version. Therefore, no such problems occured.

**Comment by venn0605** [comment]
> I tested it once in CPU version. But since the GPU version is faster, I didn't continue using the CPU version. Therefore, no such problems occured.

Thank you for your reply. When I tested it in the GPU version. I ran into this problem. (import tensorflow as tf  ImportError: DLL load failed: The tensorflow module could not be found.) I looked through several solutions, but it still does not work. Do you have any ideas about it?

**Comment by jonasmeyer1** [comment]
Did you use the correct compiler version (see above)?

**Comment by venn0605** [comment]
> Did you use the correct compiler version (see above)?

I almost give up in the GPU version. I test it in the CPU version. And the same error as you and the first member above occurred. 

'KeyError: "The name 'image_tensor:0' refers to a Tensor which does not exist. The operation, 'image_tensor', does not exist in the graph." 

Can I fix it in the CPU version? I did not find a solution in the CPU version.

**Comment by jonasmeyer1** [comment]
Have you tried to reinstall CUDA 9.0 and Tensorflow 1.11 properly?

Do you use a conda environment? I seem to remember that I switched from conda to virtualenv.

**Comment by venn0605** [comment]
> Have you tried to reinstall CUDA 9.0 and Tensorflow 1.11 properly?
> 
> Do you use a conda environment? I seem to remember that I switched from conda to virtualenv.

Yes, I use the anaconda env. I will have a try in the virtualenv. Hopefully it will work.

**Comment by philipphenkel** [comment]
We fixed an issue with the download of the weights. Automatic download should work again and additionally, I provided the links at
https://github.com/understand-ai/anonymizer/blob/master/README.md#weights

**Comment by oddhoe** [comment]
(anonymizer) p03@ViaPPS:~/anonymizer$ pytest
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-3.9.1, py-1.11.0, pluggy-1.0.0
rootdir: /home/p03/anonymizer, inifile: pytest.ini
collected 6 items                                                              

test/anonymization/anonymizer_test.py ..                                 [ 33%]
test/detection/detector_test.py F                                        [ 50%]
test/detection/weights_test.py .                                         [ 66%]
test/obfuscation/obfuscator_test.py .                                    [ 83%]
test/utils/box_test.py .                                                 [100%]

=================================== FAILURES ===================================
__________________ TestDetector.test_it_detects_obvious_faces __________________

tmp_path = PosixPath('/tmp/pytest-of-p03/pytest-12/test_it_detects_obvious_faces0')

    @staticmethod
    def test_it_detects_obvious_faces(tmp_path):
        weights_directory = tmp_path / 'weights'
        face_weights_path = get_weights_path(weights_directory, kind='face')
        download_weights(weights_directory)
    
        detector = Detector(kind='face', weights_path=face_weights_path)
        np_image = load_np_image('./test/detection/face_test_image.jpg')
    
        left_face = Box(x_min=267, y_min=64, x_max=311, y_max=184, score=0.0, kind='face')
        right_face = Box(x_min=369, y_min=68, x_max=420, y_max=152, score=0.0, kind='face')
    
>       boxes = detector.detect(np_image, detection_threshold=0.2)

test/detection/detector_test.py:33: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
anonymizer/detection/detector.py:41: in detect
    image_tensor = self.detection_graph.get_tensor_by_name('image_tensor:0')
../.virtualenvs/anonymizer/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:3664: in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
../.virtualenvs/anonymizer/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:3488: in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tensorflow.python.framework.ops.Graph object at 0x7f0599f21198>
obj = 'image_tensor:0', allow_tensor = True, allow_operation = False

    def _as_graph_element_locked(self, obj, allow_tensor, allow_operation):
      """See `Graph.as_graph_element()` for details."""
      # The vast majority of this function is figuring
      # out what an API user might be doing wrong, so
      # that we can give helpful error messages.
      #
      # Ideally, it would be nice to split it up, but we
      # need context to generate nice error messages.
    
      if allow_tensor and allow_operation:
        types_str = "Tensor or Operation"
      elif allow_tensor:
        types_str = "Tensor"
      elif allow_operation:
        types_str = "Operation"
      else:
        raise ValueError("allow_tensor and allow_operation can't both be False.")
    
      temp_obj = _as_graph_element(obj)
      if temp_obj is not None:
        obj = temp_obj
    
      # If obj appears to be a name...
      if isinstance(obj, compat.bytes_or_text_types):
        name = compat.as_str(obj)
    
        if ":" in name and allow_tensor:
          # Looks like a Tensor name and can be a Tensor.
          try:
            op_name, out_n = name.split(":")
            out_n = int(out_n)
          except:
            raise ValueError("The name %s looks a like a Tensor name, but is "
                             "not a valid one. Tensor names must be of the "
                             "form \"<op_name>:<output_index>\"." % repr(name))
          if op_name in self._nodes_by_name:
            op = self._nodes_by_name[op_name]
          else:
            raise KeyError("The name %s refers to a Tensor which does not "
                           "exist. The operation, %s, does not exist in the "
>                          "graph." % (repr(name), repr(op_name)))
E           KeyError: "The name 'image_tensor:0' refers to a Tensor which does not exist. The operation, 'image_tensor', does not exist in the graph."

../.virtualenvs/anonymizer/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:3530: KeyError
----------------------------- Captured stdout call -----------------------------
Downloading face weights to /tmp/pytest-of-p03/pytest-12/test_it_detects_obvious_faces0/weights/weights_face_v1.0.0.pb
Downloading 1CwChAYxJo3mON6rcvXsl82FMSKj82vxF into /tmp/pytest-of-p03/pytest-12/test_it_detects_obvious_faces0/weights/weights_face_v1.0.0.pb... Done.
Downloading plate weights to /tmp/pytest-of-p03/pytest-12/test_it_detects_obvious_faces0/weights/weights_plate_v1.0.0.pb
Downloading 1Fls9FYlQdRlLAtw-GVS_ie1oQUYmci9g into /tmp/pytest-of-p03/pytest-12/test_it_detects_obvious_faces0/weights/weights_plate_v1.0.0.pb... Done.
----------------------------- Captured stderr call -----------------------------
2022-04-11 17:15:40.724474: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
=============================== warnings summary ===============================
/home/p03/anonymizer/anonymizer/detection/detector.py:16: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  od_graph_def.ParseFromString(serialized_graph)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
================ 1 failed, 5 passed, 1 warnings in 2.62 seconds ================
(anonymizer) p03@ViaPPS:~/anonymizer$ 

-----------------------------
I am unable to find a solution to my issue in anonymizer, when running pytest it shows these messages as shown above.

Any one have a solution?

Graphics card
00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06) (prog-if 00 [VGA controller])
Memory at f7f3d000 (32-bit, non-prefetchable) [size=4K]

Ubuntu 18.04
TF 1.11.0
