### ISSUE TITLE
Error with downloading weights

### ISSUE THREAD

**Issue by FantineFu** [understand-ai/anonymizer#17]
Hi, there's something wrong when I download the weights, and I've checked my connection is fine. Is there anything wrong with the weights source? The url can't be opened directly, could you please kindly provide a available address to download the weights?

Here is my error when run pytest:

raise ConnectionError(e, request=request)
E           requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1CwChAYxJo3mON6rcvXsl82FMSKj82vxF (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f33d979da58>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

../miniconda3/envs/anonyai/lib/python3.6/site-packages/requests/adapters.py:516: ConnectionError
--------------------------------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------------------------------
Downloading face weights to /tmp/pytest-of-root/pytest-1/test_it_downloads_weights0/weights/weights_face_v1.0.0.pb
Downloading 1CwChAYxJo3mON6rcvXsl82FMSKj82vxF into /tmp/pytest-of-root/pytest-1/test_it_downloads_weights0/weights/weights_face_v1.0.0.pb...

**Comment by philipphenkel** [comment]
We fixed an issue with the download of the weights. Automatic download should work again and additionally, I provided the links at
https://github.com/understand-ai/anonymizer/blob/master/README.md#weights
