### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by qume** [understand-ai/anonymizer#20]
I am trying to use this on a Jetson Xavier NX with 8gb of shared GPU/CPU ram.

It seems to want to use around 14GB total. Is that expected behaviour? Does anyone have suggestions to reduce that significantly?

I tried using
tf_config.gpu_options.allow_growth=True

for both the obfuscator and the detector, but it doesn't seem to help, leading me to believe the model really does need that much GPU memory?

**Comment by L-Reichardt** [comment]
For my application I am using 10.7 GB, which also runs some other lightweight tasks. Id say maybe 10 GB is just the neural networks. Unfortunately, the face detection and lisence plate detection are each done by a single neural network. If you dont need "realtime" performance, you could try rebuilding the neural network graph for each task. This could somewhat reduce memory usage.
