### ISSUE TITLE
Anonymizer on video file mp4

### ISSUE THREAD

**Issue by valeriodeluca** [understand-ai/anonymizer#25]
Dear UAI,
Thanks for your anonymizer. 
In your opinion, is it possible use the anonymizer to blur faces and license plates on video file mp4 like the following?

From:
[https://youtu.be/PcKXjFCC2f0?t=778](https://youtu.be/PcKXjFCC2f0?t=778)
To:
[https://youtu.be/PcKXjFCC2f0?t=809](https://youtu.be/PcKXjFCC2f0?t=809)

Here you can see an example similar to the videos I am processing, in these 30 seconds there are both faces of people and license plates of cars.

I need to remove the PII Personal Identifiable Information from videos made on a bicycle with the cyclist's POV Point Of View cam.

I've seen that sometimes a simple WHILE loop is enough to apply a tool from photos to videos like this:
[https://pysource.com/2021/05/21/blur-faces-in-real-time-with-opencv-mediapipe-and-python/#:~:text=add(background%2C%20face_extracted)-,Take,-out%20the%20face](https://pysource.com/2021/05/21/blur-faces-in-real-time-with-opencv-mediapipe-and-python/#:~:text=add(background%2C%20face_extracted)-,Take,-out%20the%20face)

I ask if it is also possible with anonymizer.

Thanks for your availability
Happy 2022

**Comment by amrragab8080** [comment]
I have a similar use-case using anonymizer. What I did was dockerize anonymizer with ffmpeg and use ffmpeg to take my mp4 file -> split frames -> run anonymizer on the frames -> ffmpeg to reassemble the video.

**Comment by fernandosngular** [comment]
Problem with it is what model used in this library: https://docs.google.com/file/d/1Fls9FYlQdRlLAtw-GVS_ie1oQUYmci9g is very big, then, process every image... is hard

**Comment by valeriodeluca** [comment]
Thank you @fernandosngular.
I did frame by frame, I used TensorFlow for not GPU. I will try with TensorFlow GPU python lib to check out if I get time reduction processing.
